---
services:
  - type: web
    name: pivot-api
    env: go
    goVersion: 1.25.3
    branch: master
    buildCommand: cd server && go build -o server
    startCommand: ./server/server
    autoDeploy: true
    plan: free
  - type: static-site
    name: pivot-web
    env: static
    branch: master
    publishPath: web
    autoDeploy: true
    plan: free
